# Generated by Django 6.0.2 on 2026-03-03 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_EDIT', 'Needs Editing')], default='PENDING', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('preferred_password', models.CharField(max_length=128)),
                ('hometown', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pending_photos/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('auto_approved', models.BooleanField(default=False)),
                ('approval_mode_used', models.CharField(blank=True, max_length=20, null=True)),
                ('diocese', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.diocese')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.state')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUAL', 'Manual Approval - Admin reviews each'), ('AUTOMATIC', 'Automatic Approval - Instant account creation'), ('HYBRID', 'Hybrid - Admin chooses per submission')], default='MANUAL', max_length=20)),
                ('auto_approve_domains', models.TextField(blank=True, help_text='Comma-separated email domains (e.g., @pjps.edu)')),
                ('notify_admin_on_auto_approve', models.BooleanField(default=True)),
                ('notify_user_on_approval', models.BooleanField(default=True)),
                ('auto_approve_dioceses', models.ManyToManyField(blank=True, to='albums.diocese')),
            ],
            options={
                'verbose_name': 'Approval Settings',
                'verbose_name_plural': 'Approval Settings',
            },
        ),
        migrations.CreateModel(
            name='StaffPending',
            fields=[
                ('pendingapproval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.pendingapproval')),
                ('staff_category', models.CharField(choices=[('ADMIN', 'Administrative'), ('ACADEMIC', 'Academic'), ('LIBRARY', 'Library'), ('TECHNICAL', 'Technical'), ('SUPPORT', 'Support')], default='ACADEMIC', max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Pending Staff',
                'verbose_name_plural': 'Pending Staff',
            },
            bases=('registration.pendingapproval',),
        ),
        migrations.CreateModel(
            name='StudentPending',
            fields=[
                ('pendingapproval_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.pendingapproval')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year_level', models.CharField(blank=True, max_length=20)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Pending Student',
                'verbose_name_plural': 'Pending Students',
            },
            bases=('registration.pendingapproval',),
        ),
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_APPROVED', 'Auto Approved'), ('REQUEST_CHANGES', 'Requested Changes')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='registration.pendingapproval')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pendingapproval',
            index=models.Index(fields=['status'], name='registratio_status_0bd4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingapproval',
            index=models.Index(fields=['registration_number'], name='registratio_registr_b29c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingapproval',
            index=models.Index(fields=['submitted_at'], name='registratio_submitt_49b3ea_idx'),
        ),
    ]
