# Generated by Django 6.0.2 on 2026-03-06 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('build_number', models.CharField(max_length=20)),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AppFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='apps/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('md5_checksum', models.CharField(blank=True, max_length=32)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='downloads.appversion')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('app_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downloads.appfile')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
