# Generated by Django 6.0.2 on 2026-03-03 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('title', models.CharField(default='Remarks', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remark_type', models.CharField(choices=[('GENERAL', 'General Note'), ('ACADEMIC', 'Academic'), ('BEHAVIORAL', 'Behavioral'), ('ACHIEVEMENT', 'Achievement'), ('ATTENDANCE', 'Attendance'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('INTERNAL', 'Internal'), ('PUBLIC', 'Public')], default='INTERNAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='remark_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_remarks', to=settings.AUTH_USER_MODEL)),
                ('remark_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='remarks.remarkbook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemarkComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='remarks.remark')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
