# choices.py

# Nigerian States
STATE_CHOICES = [
    ('', 'Select State'),
    ('abia', 'Abia'),
    ('adamawa', 'Adamawa'),
    ('akwa_ibom', 'Akwa Ibom'),
    ('anambra', 'Anambra'),
    ('bauchi', 'Bauchi'),
    ('bayelsa', 'Bayelsa'),
    ('benue', 'Benue'),
    ('borno', 'Borno'),
    ('cross_river', 'Cross River'),
    ('delta', 'Delta'),
    ('ebonyi', 'Ebonyi'),
    ('edo', 'Edo'),
    ('ekiti', 'Ekiti'),
    ('enugu', 'Enugu'),
    ('fct', 'FCT Abuja'),
    ('gombe', 'Gombe'),
    ('imo', 'Imo'),
    ('jigawa', 'Jigawa'),
    ('kaduna', 'Kaduna'),
    ('kano', 'Kano'),
    ('katsina', 'Katsina'),
    ('kebbi', 'Kebbi'),
    ('kogi', 'Kogi'),
    ('kwara', 'Kwara'),
    ('lagos', 'Lagos'),
    ('nasarawa', 'Nasarawa'),
    ('niger', 'Niger'),
    ('ogun', 'Ogun'),
    ('ondo', 'Ondo'),
    ('osun', 'Osun'),
    ('oyo', 'Oyo'),
    ('plateau', 'Plateau'),
    ('rivers', 'Rivers'),
    ('sokoto', 'Sokoto'),
    ('taraba', 'Taraba'),
    ('yobe', 'Yobe'),
    ('zamfara', 'Zamfara'),
]

# Catholic Dioceses
DIOCESE_CHOICES = [
    ('', 'Select Diocese'),
    ('abuja', 'Archdiocese of Abuja'),
    ('lagos', 'Archdiocese of Lagos'),
    ('ibadan', 'Archdiocese of Ibadan'),
    ('benin', 'Archdiocese of Benin City'),
    ('calabar', 'Archdiocese of Calabar'),
    ('jos', 'Archdiocese of Jos'),
    ('kaduna', 'Archdiocese of Kaduna'),
    ('onitsha', 'Archdiocese of Onitsha'),
    ('owerri', 'Archdiocese of Owerri'),

    ('awka', 'Diocese of Awka'),
    ('nnewi', 'Diocese of Nnewi'),
    ('ekwulobia', 'Diocese of Ekwulobia'),
    ('aguleri', 'Diocese of Aguleri'),
    ('awgu', 'Diocese of Awgu'),

    ('enugu', 'Diocese of Enugu'),
    ('nsukka', 'Diocese of Nsukka'),
    ('aba', 'Diocese of Aba'),
    ('umuahia', 'Diocese of Umuahia'),
    ('okigwe', 'Diocese of Okigwe'),
    ('uyo', 'Diocese of Uyo'),
    ('warri', 'Diocese of Warri'),
]