# Generated by Django 6.0.2 on 2026-03-03 22:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('position', models.CharField(max_length=200)),
                ('employment_date', models.DateField()),
                ('work_email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('work_phone', models.CharField(max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('office_hours', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('is_active', models.BooleanField(default=True)),
                ('is_current_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Staff categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryStaff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='library_details', serialize=False, to='staff.staff')),
                ('library_section', models.CharField(choices=[('CIRCULATION', 'Circulation Desk'), ('REFERENCE', 'Reference Section'), ('CATALOGING', 'Cataloging'), ('DIGITAL', 'Digital Library'), ('ARCHIVES', 'Archives'), ('PERIODICALS', 'Periodicals'), ('ADMIN', 'Library Administration')], max_length=50)),
                ('librarian_rank', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.staffcategory'),
        ),
        migrations.CreateModel(
            name='AdministrativeStaff',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_details', serialize=False, to='staff.staff')),
                ('admin_role', models.CharField(max_length=100)),
                ('manages_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.department')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.administrativestaff')),
            ],
            options={
                'verbose_name_plural': 'Administrative staff',
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='staff_staff_staff_i_1228db_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['first_name', 'last_name'], name='staff_staff_first_n_f22f40_idx'),
        ),
    ]
