# Generated by Django 6.0.2 on 2026-03-22 21:20

import albums.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='class_teacher',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='additional_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), albums.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), albums.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), albums.models.validate_image_size]),
        ),
    ]
