# Generated by Django 6.0.2 on 2026-03-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_classgroup_class_teacher_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='albums.yearlevel'),
        ),
        migrations.DeleteModel(
            name='ClassGroup',
        ),
    ]
